import Header from "@/components/common/Header/Header";
import LoginForm from "@/components/common/LoginForm/LoginForm";
import Head from "next/head";
import styles from "./Login.module.scss";

export default function Login() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className={styles.container}>
          <LoginForm />
        </div>
      </main>
    </>
  );
}
