import Header from "@/components/common/Header/Header";
import Head from "next/head";
import styles from "../../../../components/Admin/MainPage/MainAdminPage.module.css";
import Navigation from "@/components/Admin/navigation";
import { Box, Paper } from "@mui/material";
import { useEffect, useState } from "react";
import api from "@/pages/api/apiRequest";
import serverApi from "@/pages/api/auth";
import AddNews from "@/components/Admin/components/addNews";

export default function EditNewsPage() {
  const [item, setItem] = useState(null);

  async function get() {
    const { data: authData } = await api("profile");

    if (authData) {
      setItem(true);
    }
  }

  useEffect(() => {
    get();
  }, []);

  return (
    <>
      <Head>
        <title>ТПА Крепеж</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ minHeight: "100vh" }}>
        <Header />
        {item && (
          <Box className={styles.body}>
            <Box className={styles.main}>
              <Paper elevation={0} className={styles.infoPanel}>
                <Box className={styles.infoPanelTitle}>
                  <AddNews />
                </Box>
              </Paper>
            </Box>
          </Box>
        )}
        <Navigation />
      </main>
    </>
  );
}
