import Header from "@/components/common/Header/Header";
import Head from "next/head";
import styles from "@/styles/Admin.module.scss";
import serverApi from "@/pages/api/auth";
import EditItems from "@/components/Admin/components/editItems";
import Navigation from "@/components/Admin/navigation";

export default function EditItemPage({ item, categories }) {
  return (
    <>
      <Head>
        <title>ТПА Крепеж</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ minHeight: "100vh" }}>
        <Header />
        <div className={styles.container}>
          <EditItems item={item} categories={categories} />
          <Navigation />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps({ res, query }) {
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=3600, stale-while-revalidate=59"
  );
  const { data: responseData } = await serverApi("items");
  const { data: catsData } = await serverApi("categories");

  const itemData = responseData.find((i) => i.id.toString() === query.id);
  if (itemData && catsData) {
    return {
      props: {
        item: itemData,
        categories: catsData,
      },
    };
  } else {
    return {
      notFound: true,
    };
  }
}
