import Header from "@/components/common/Header/Header";
import Head from "next/head";
import styles from "../../../../components/Admin/MainPage/MainAdminPage.module.css";
import serverApi from "@/pages/api/auth";
import Navigation from "@/components/Admin/navigation";
import AddItems from "@/components/Admin/components/addItems";
import { Box, Paper } from "@mui/material";

export default function EditItem({ categories }) {
  return (
    <>
      <Head>
        <title>ТПА Крепеж</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ minHeight: "100vh" }}>
        <Header />
        <div className={styles.container}>
          <Box className={styles.body}>
            <Box className={styles.main}>
              <Paper elevation={0} className={styles.infoPanel}>
                <Box className={styles.infoPanelTitle}>
                  <AddItems categories={categories} />
                </Box>
              </Paper>
            </Box>
          </Box>
          <Navigation />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps({ res, query }) {
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=3600, stale-while-revalidate=59"
  );
  const { data: catsData } = await serverApi("categories");

  if (catsData) {
    return {
      props: {
        categories: catsData,
      },
    };
  } else {
    return {
      notFound: true,
    };
  }
}
