import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Header from "@/components/common/Header/Header";
import Search from "@/components/common/Search/Search";
import news from "../../public/news_mock.png";
import Categories from "@/components/common/Categories/Categories";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <div className={styles.container}>
          <Search />
        </div>
        <div
          style={{
            width: "100%",
            marginBlock: 64,
            display: "flex",
            justifyContent: "center",
          }}
        >
          <Image src={news} width="100%" style={{ marginleft: "auto" }} />
        </div>
        <Categories />
      </main>
    </>
  );
}
