import Header from "@/components/common/Header/Header";
import Head from "next/head";
import styles from "../../../../components/Admin/MainPage/MainAdminPage.module.css";
import Navigation from "@/components/Admin/navigation";
import { Box, Paper } from "@mui/material";
import { useEffect, useState } from "react";
import api from "@/pages/api/apiRequest";
import EditNews from "@/components/Admin/components/editNews";
import serverApi from "@/pages/api/auth";

export default function EditNewsPage({ article }) {
  const [item, setItem] = useState(null);

  async function get() {
    const { data: authData } = await api("profile");

    if (authData) {
      setItem(true);
    }
  }

  useEffect(() => {
    get();
  }, []);

  return (
    <>
      <Head>
        <title>ТПА Крепеж</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ minHeight: "100vh" }}>
        <Header />
        {item && (
          <Box className={styles.body}>
            <Box className={styles.main}>
              <Paper elevation={0} className={styles.infoPanel}>
                <Box className={styles.infoPanelTitle}>
                  <EditNews item={article} />
                </Box>
              </Paper>
            </Box>
          </Box>
        )}
        <Navigation />
      </main>
    </>
  );
}

export async function getServerSideProps({ res, query }) {
  const newsId = parseInt(query.id);
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=3600, stale-while-revalidate=59"
  );
  const { data: responseData } = await serverApi("news");

  const itemData = responseData.find((i) => i.id === newsId);
  if (itemData) {
    return {
      props: {
        article: itemData,
      },
    };
  } else {
    return {
      notFound: true,
    };
  }
}
