import Header from "@/components/common/Header/Header";
import Head from "next/head";
import { useEffect, useState } from "react";
import api from "../api/apiRequest";
import { useRouter } from "next/router";
import { CircularProgress } from "@mui/material";
import MainAdminPage from "@/components/Admin/MainPage/MainAdminPage";

export default function Admin() {
  const router = useRouter();
  const [login, setLogin] = useState(false);
  const [usedPush, setUsedPush] = useState(false);
  async function get() {
    const { data: resData } = await api("profile");
    if (!resData) {
      if (!usedPush) {
        window.location.href = "/login";
        setUsedPush(true);
      }
    } else {
      setLogin(true);
    }
  }
  useEffect(() => {
    let mounted = true;

    //check if component is currently mounted
    if (mounted) {
      get();
    }
    //cleanup side effects before unmounting
    return () => {
      mounted = false;
    };
  }, []);

  useEffect(() => {
    router.prefetch("/login");
  }, [router]);
  return (
    <>
      {login ? (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <Header />
            <MainAdminPage />
          </main>
        </>
      ) : (
        <div
          style={{
            width: "100%",
            height: "90vh",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <CircularProgress />
        </div>
      )}
    </>
  );
}
